### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by abhish2** [tuantyler/Microsoft-Rewards-Central#1]
can you add feature to earn points automatically

**Comment by tuantyler21** [comment]
The feature already exists and is automatically redeemed if passed 3AM daily. However, it seems like there is a bug with background.js continuity. I will take a look into that and let you know when it’s done.

**Comment by tuantyler21** [comment]
I'm happy to let you know that the problem has been fixed. The bug with background.js continuity has been resolved and the feature to earn points automatically is now working as expected. You should be able to redeem your points automatically after passing 3AM daily.

**Comment by abhish2** [comment]
> I'm happy to let you know that the problem has been fixed. The bug with background.js continuity has been resolved and the feature to earn points automatically is now working as expected. You should be able to redeem your points automatically after passing 3AM daily.

works well. Loved it !
